version: '3'
services:
  bloc-db:
    image: "postgres:latest"
    container_name: bloc-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - /opt/bloc/database/:/data/db
      - ./database:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bloc 

  bloc-api:
    build: ./bloc-backend/
    container_name: bloc-api
    volumes:
      - /opt/bloc/storage/:/opt/bloc/storage
    environment:
      - DB_URL=postgresql://postgres:12345@bloc-db:5432/bloc
      - STORAGE_DIR=/opt/bloc/storage
      - SERVER_DOMAIN=coldwire.org
      - SERVER_HTTPS=true
      - STORAGE_QUOTA=4096
    ports:
      - 3001:3000
    depends_on:
      - bloc-db
    links:
      - bloc-db

  bloc-font:
    build:
      context: ./bloc-frontend/
      args:
        - API_BASE=https://bloc.coldwire.org/api
    container_name: bloc-front
    ports:
      - 4000:3000
    depends_on:
      - bloc-api
    links:
      - bloc-api