[server]
address = "0.0.0.0"
port = "3002"

[database]
driver = "postgres"

  [database.postgres]
  address = "127.0.0.1"
  port = "5432"
  user = "postgres"
  password = "4llc0ps4re64st4rds"
  name = "bloc"

[storage]
driver = "fs"
quota = "4G"

  [storage.fileSystem]
  path = "./test"

  [storage.s3]
  address = ""
  bucket = "bloc"
  id = ""
  secret = ""
  token = ""
  region = ""

  [storage.polar]
  url = "unix:///var/run/polar.sock"
  secret = "acab"

[oauth]
server = "http://127.0.0.1:3003/"
id = "bloc"
secret = "acab1312"
callback = "http://127.0.0.1:3002/api/user/auth/oauth2/callback"
  
